export const CBDATA_GET_INVESTOR_SUBMITTED = 'CBDATA_GET_INVESTOR_SUBMITTED';
export const CBDATA_GET_INVESTOR_SUCCEEDED = 'CBDATA_GET_INVESTOR_SUCCEEDED';
export const CBDATA_GET_INVESTOR_FAILED = 'CBDATA_GET_INVESTOR_FAILED';
export const CBDATA_GET_INVESTOR_DISMISSED = 'CBDATA_GET_INVESTOR_DISMISSED';

export const CBDATA_GET_INVESTORUUIDS_SUBMITTED = 'CBDATA_GET_INVESTORUUIDS_SUBMITTED';
export const CBDATA_GET_INVESTORUUIDS_SUCCEEDED = 'CBDATA_GET_INVESTORUUIDS_SUCCEEDED';
export const CBDATA_GET_INVESTORUUIDS_COMPLETED = 'CBDATA_GET_INVESTORUUIDS_COMPLETED';
export const CBDATA_GET_INVESTORUUIDS_FAILED = 'CBDATA_GET_INVESTORUUIDS_FAILED';
export const CBDATA_GET_INVESTORUUIDS_DISMISSED = 'CBDATA_GET_INVESTORUUIDS_DISMISSED';

export const AIRTABLE_POST_INVESTOR_SUBMITTED = 'AIRTABLE_POST_INVESTOR_SUBMITTED';
export const AIRTABLE_POST_INVESTOR_SUCCEEDED = 'AIRTABLE_POST_INVESTOR_SUCCEEDED';
export const AIRTABLE_POST_INVESTOR_FAILED = 'AIRTABLE_POST_INVESTOR_FAILED';
export const AIRTABLE_POST_INVESTOR_DISMISSED = 'AIRTABLE_POST_INVESTOR_DISMISSED';

export const SEARCH_SET_SEARCHTEXT = 'SEARCH_SET_SEARCHTEXT';

export const TOSAVE_DATA_SET = 'TOSAVE_DATA_SET';

export const AIRTABLE_GET_INVESTORS_REQUESTED = 'AIRTABLE_GET_INVESTORS_REQUESTED';
export const AIRTABLE_GET_INVESTORS_SUCCEEDED = 'AIRTABLE_GET_INVESTORS_SUCCEEDED';
export const AIRTABLE_GET_INVESTORS_COMPLETED = 'AIRTABLE_GET_INVESTORS_COMPLETED';
export const AIRTABLE_GET_INVESTORS_FAILED = 'AIRTABLE_GET_INVESTORS_FAILED';
export const AIRTABLE_GET_INVESTORS_DISMISSED = 'AIRTABLE_GET_INVESTORS_DISMISSED';

export const AIRTABLE_PATCH_INVESTOR_SUBMITTED = 'AIRTABLE_PATCH_INVESTOR_SUBMITTED';
export const AIRTABLE_PATCH_INVESTOR_SUCCEEDED = 'AIRTABLE_PATCH_INVESTOR_SUCCEEDED';
export const AIRTABLE_PATCH_INVESTOR_FAILED = 'AIRTABLE_PATCH_INVESTOR_FAILED';
export const AIRTABLE_PATCH_INVESTOR_DISMISSED = 'AIRTABLE_PATCH_INVESTOR_DISMISSED';
