export const CBDATA_GET_INVESTOR_SUBMITTED = 'CBDATA_GET_INVESTOR_SUBMITTED';
export const CBDATA_GET_INVESTOR_SUCCEEDED = 'CBDATA_GET_INVESTOR_SUCCEEDED';
export const CBDATA_GET_INVESTOR_FAILED = 'CBDATA_GET_INVESTOR_FAILED';
export const CBDATA_GET_INVESTOR_DISMISSED = 'CBDATA_GET_INVESTOR_DISMISSED';

export const AIRTABLE_POST_INVESTOR_SUBMITTED = 'AIRTABLE_POST_INVESTOR_SUBMITTED';
export const AIRTABLE_POST_INVESTOR_SUCCEEDED = 'AIRTABLE_POST_INVESTOR_SUCCEEDED';
export const AIRTABLE_POST_INVESTOR_FAILED = 'AIRTABLE_POST_INVESTOR_FAILED';
export const AIRTABLE_POST_INVESTOR_DISMISSED = 'AIRTABLE_POST_INVESTOR_DISMISSED';

export const SEARCH_SET_SEARCHTEXT = 'SEARCH_SET_SEARCHTEXT';

export const TOSAVE_DATA_SET = 'TOSAVE_DATA_SET';
